// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// TestOKCode is the HTTP code returned for type TestOK
const TestOKCode int = 200

/*TestOK Success

swagger:response testOK
*/
type TestOK struct {
}

// NewTestOK creates TestOK with default headers values
func NewTestOK() *TestOK {

	return &TestOK{}
}

// WriteResponse to the client
func (o *TestOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(200)
}
