settings:
  legacy:
    force: false
    interval: 0s
server:
  status: false
  open: false
  port: 5001
  host: localhost
schema:
- name: golang-rest-api-template
  path: app/
  commands:
    run:
      status: true
  watcher:
    extensions:
    - go
    paths:
    - /
    ignored_paths:
    - .git
    - .realize
    - vendor
