version: '3'
services:
  web:
    build:
      context: .
      dockerfile: ./docker/web/Dockerfile
    command: air -c .air.toml
    tty: true
    stdin_open: true
    ports:
      - '5001:5001'
    volumes:
      - ./app:/go/src/golang-rest-api-template
      - pkg:/go/pkg
volumes:
  pkg:
    driver: local
