version: '3'
services:
  web:
    build: .
    command: realize start --server
    tty: true
    stdin_open: true
    ports:
      - '5001:5001'
    volumes:
      - .:/go/src/golang-rest-api-template
