swagger: "2.0"
info:
  version: "1.0.0"
  title: "sample"
host: "localhost:5001"
basePath: "/api"
schemes:
  - "http"
consumes:
  - "application/json"
produces:
  - "application/json"
paths:
  /test:
    get:
      operationId: test
      responses:
        200:
          description: Success
          schema:
            type: string
            description: contains the actual greeting as plain text
